# Generated by Django 3.1.5 on 2021-01-17 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import mtu.models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mtu.models.Album_directory_path)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('album_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Goddess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(blank=True, max_length=100)),
                ('ranking', models.PositiveIntegerField(blank=True, default=0)),
                ('hotpoint', models.PositiveIntegerField(blank=True, default=0)),
                ('hometown', models.CharField(blank=True, max_length=100)),
                ('career', models.CharField(default='模特', max_length=100)),
                ('thumb', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mtu.models.Goddess_directory_path)),
                ('birthday', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True, default=30)),
                ('body_height', models.PositiveIntegerField(blank=True, default=165)),
                ('body_weight', models.PositiveIntegerField(blank=True, default=40)),
                ('body_bra', models.CharField(blank=True, default=88, max_length=100)),
                ('body_waist', models.PositiveIntegerField(blank=True, default=60)),
                ('body_butt', models.PositiveIntegerField(blank=True, default=88)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('ranking',),
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('thumb', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mtu.models.Institution_directory_path)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('created', models.DateField(blank=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=100)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=mtu.models.AlbumImage_directory_path)),
                ('alt', models.CharField(default=uuid.uuid4, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=70)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mtu.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='mtu.goddess'),
        ),
        migrations.AddField(
            model_name='album',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album', to='mtu.institution'),
        ),
    ]
