# Generated by Django 3.1.5 on 2021-01-17 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import friendlink.models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '收藏网址类别',
                'verbose_name_plural': '收藏网址类别',
            },
        ),
        migrations.CreateModel(
            name='Friend_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, max_length=200, verbose_name='摘要')),
                ('url', models.URLField(verbose_name='网址')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=friendlink.models.link_logo_path)),
                ('link_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_link', to='friendlink.link_type')),
            ],
            options={
                'verbose_name': '收藏的网址',
                'verbose_name_plural': '收藏的网址',
            },
        ),
    ]
